import {
  AccountCircle,
  Add,
  ArrowBack,
  ArrowForward,
  Article,
  BackHand,
  ChatBubble,
  Check,
  Close,
  CloudUpload,
  DeleteForever,
  Edit,
  EditOutlined,
  Email,
  Info,
  InsertDriveFile,
  KeyboardArrowDown,
  KeyboardArrowUp,
  Label,
  LineWeight,
  List,
  Menu,
  Photo,
  Preview,
  Schedule,
  Search,
  SmsRounded,
  Textsms,
  Visibility,
  VisibilityOff,
  WarningRounded,
} from '@mui/icons-material';

import { type IconMapper } from './icon.types';

export const ICON_MAPPER: IconMapper = {
  'account-circle': AccountCircle,
  add: Add,
  'arrow-back': ArrowBack,
  'arrow-down': KeyboardArrowDown,
  'arrow-forward': ArrowForward,
  'arrow-up': KeyboardArrowUp,
  article: Article,
  chat: ChatBubble,
  check: Check,
  close: Close,
  'cloud-upload': CloudUpload,
  delete: DeleteForever,
  email: Email,
  file: InsertDriveFile,
  hand: BackHand,
  info: Info,
  label: Label,
  'line-weight': LineWeight,
  list: List,
  menu: Menu,
  message: Textsms,
  pencil: EditOutlined,
  photo: Photo,
  'pencil-edit': Edit,
  schedule: Schedule,
  search: Search,
  preview: Preview,
  sms: SmsRounded,
  visibility: Visibility,
  'visibility-off': VisibilityOff,
  warning: WarningRounded,
};
